import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

DATA_DIR = "data"
LOGS_DIR = "logs"

EMAIL_SENDER = os.getenv("EMAIL")
EMAIL_PASSWORD = os.getenv("EMAIL_PASSWORD")
EMAIL_RECEIVER = os.getenv("EMAIL_RECEIVER")

SYMBOL = ["NVDA", "AAPL", "ABBV", "PLTR"]
PAPER_TRADE_SYMBOLS = []
PAPER_TRADE_NOTES = {}

BUY_THRESHOLD = 0.55
SELL_THRESHOLD = 0.45
PYRAMID_THRESHOLD = 0.65
AAPL_BUY_THRESHOLD = 0.60

USE_ARTIFACT_THRESHOLDS = True
ARTIFACT_THRESHOLD_FALLBACK = 0.55

MODEL_ENTRY_BUFFER = 0.02
MODEL_EXIT_BUFFER = 0.02
MODEL_REBUY_BUFFER = 0.04
MODEL_PYRAMID_BUFFER = 0.08

SPY_USE_ARTIFACT_THRESHOLDS = True
SPY_MODEL_ENTRY_BUFFER = 0.03
SPY_MODEL_EXIT_BUFFER = 0.02

REBUY_THRESHOLD = BUY_THRESHOLD + 0.06
REBUY_COOLDOWN_MINUTES = 45
ALLOW_SAME_DAY_REBUY = True

INTRADAY_WEIGHT = 0.65
MIN_INTRADAY_BARS_FOR_FEATURES = 25
RS_MARGIN = 0.05
USE_MULTICLASS_MODELS = False

SPY_SYMBOL = "SPY"
WEAK_PROB_THRESHOLD = 0.50
WEAK_RATIO_THRESHOLD = 0.50
SPY_ENTRY_THRESHOLD = 0.70
SPY_EXIT_THRESHOLD = 0.50
SPY_RISK_FRACTION = 1.0
SPY_MUTUAL_EXCLUSIVE = True

INTRADAY_MOM_TRIG = 0.0030
INTRADAY_VOL_TRIG = 0.0030

INTRADAY_REGIME_OVERRIDES = {
    "NVDA": {"mom_trig": 0.0035, "vol_trig": 0.0032},
    "PLTR": {},
    "SPY": {"mom_trig": 0.0030, "vol_trig": 0.0020},
}

MOM_HOLD = 0.003
VOL_HOLD = 0.0035

TRAIN_SYMBOLS = ["NVDA", "AAPL", "SPY", "ABBV", "PLTR"]
SHAP_TOP_N = 40

STOP_LOSS = 0.97
TAKE_PROFIT = None
TRAIL_STOP = 0.985
TRAIL_ACTIVATE = 1.02
RISK_FRACTION = 0.5
MAX_LOSS_PER_TRADE = 10.00

MAX_POSITION_SIZE_PCT = 0.90
MAX_POSITION_SIZE_DOLLARS = None
MIN_RETURN_THRESHOLD = 0.002

DIP_BUY_ENABLED = True
DIP_BUY_MIN_PROB = 0.75
DIP_BUY_THRESHOLD = 0.015

PDT_TIERING_ENABLED = True
PDT_SAMEDAY_STOP_BLOCK = 0.020
PDT_EMERGENCY_STOP = None
PDT_EMERGENCY_MAX_PER_DAY = 1
PDT_EMERGENCY_PROB_THRESH = 0.40

PRE_MARKET_ENABLED = True
PRE_MARKET_MIN_PROB = 0.55
PRE_MARKET_MAX_ALLOCATION = 1.0
PRE_MARKET_LIMIT_BUFFER = 0.002
PRE_MARKET_SYMBOLS = SYMBOL
PRE_MARKET_ALLOW_SHORT_SELLING = True
PRE_MARKET_MIN_SELL_PROB = 0.30
PRE_MARKET_SHORT_ALLOCATION = 0.10

PRE_MARKET_SCAN_HOUR = 9
LIMIT_BUFFER_PCT = 0.01

TIMEZONE = "US/Eastern"

SCRIPT_DIR = Path(__file__).resolve().parent
BASE_DIR = SCRIPT_DIR.parent
MODEL_DIR = BASE_DIR / "models"

def get_model_path(symbol):
    os.makedirs(MODEL_DIR, exist_ok=True)
    return os.path.join(MODEL_DIR, f"model_{symbol}.pkl")